#pragma once

namespace texas_algorithm
{

  // GenHandN selects the public-card count for the exhaustive 1v1 calculation
  // (0-4). Set it before generating, mirroring Java's static GenHandUtil.N.
  extern int GenHandN;

  // GenHandGenKey generates the exhaustive 1v1 win-rate files under hand{N}/
  // for every 2-card hand and N-card public cards. It requires the lookup
  // tables generated by GenKey/GenOpt to be present.
  void GenHandGenKey();

} // namespace texas_algorithm
