package texas_algorithm

import (
	"fmt"
	"os"
	"runtime"
	"sort"
	"strconv"
	"sync"
	"time"
)

// Package-level state for the exhaustive 1v1 hand calculation, mirroring the
// static fields of Java's GenHandUtil. Set GenHandN before generating.
var (
	GenHandN          = 6
	genHandTotalHand  int64
	genHandTotalPub   int64 = 1
	genHandTotal      int64 = 1
	genHandTotalCalc  int64 = 1
	genHandTotalKey   int64
	genHandLastPrint  int
	genHandBeginPrint int64
	genHandMu         sync.Mutex
)

type genHandCalcData struct {
	win   int64
	lose  int64
	tie   int64
	total int64
}

// GenHandGenKey generates the exhaustive 1v1 win-rate files under hand{N}/ for
// every 2-card hand and N-card public cards. It requires the lookup tables
// generated by GenKey/GenOpt to be present.
func GenHandGenKey() {
	genHandTotalPub = 1
	for i := 0; i < GenHandN; i++ {
		genHandTotalPub *= GenNum - 2 - int64(i)
	}
	for i := GenHandN; i >= 1; i-- {
		genHandTotalPub /= int64(i)
	}
	genHandTotalHand = (GenNum * (GenNum - 1)) / 2
	genHandTotal = genHandTotalPub * genHandTotalHand

	genHandTotalCalc = 1
	for i := 0; i < 5-GenHandN; i++ {
		genHandTotalCalc *= GenNum - 2 - int64(GenHandN) - int64(i)
	}
	for i := 5 - GenHandN; i >= 1; i-- {
		genHandTotalCalc /= int64(i)
	}
	for i := 0; i < 2; i++ {
		genHandTotalCalc *= GenNum - 7 - int64(i)
	}
	for i := 2; i >= 1; i-- {
		genHandTotalCalc /= int64(i)
	}

	Load()

	os.MkdirAll("hand"+strconv.Itoa(GenHandN), 0755)

	genHandBeginPrint = time.Now().UnixMilli()
	genHandTotalKey = 0
	genHandLastPrint = 0

	genHandCard()

	fmt.Println("genKey finish", genHandTotal)
}

func genHandCard() {
	list := genAllCards()

	hand := make([]int, 2)
	Permutation(list, 0, 0, 2, hand, func(hand []int) {
		genHandOnHand(hand)
	})
}

func genHandOnHand(hand []int) {
	name := "hand" + strconv.Itoa(GenHandN) + "/texas_hand_" + ToString(int64(hand[0]*100+hand[1])) + ".txt"
	if fileExists(name) {
		return
	}
	list1 := removeCounts(genAllCards(), hand)

	f, err := os.Create(name)
	if err != nil {
		fmt.Println(err)
		return
	}

	pub := make([]int, GenHandN)
	var wg sync.WaitGroup
	sem := make(chan struct{}, runtime.NumCPU())
	Permutation(list1, 0, 0, GenHandN, pub, func(pub []int) {
		fpub := append([]int{}, pub...)
		wg.Add(1)
		sem <- struct{}{}
		go func() {
			defer func() {
				<-sem
				wg.Done()
			}()
			genHandCardSave(f, hand, fpub)
		}()
	})
	wg.Wait()

	f.Close()
}

func genHandCardSave(out *os.File, hand, pub []int) {
	h := GenCardBindInts(hand)
	p := GenCardBindInts(pub)
	for i := 0; i < GenHandN; i++ {
		h *= 100
	}
	h += p

	pp := genHandCalc(hand, pub)

	tmp := fmt.Sprint(h) + " " + strconv.FormatFloat(pp, 'g', -1, 64) + " " + ToString(h) + "\n"

	genHandMu.Lock()
	out.WriteString(tmp)
	genHandTotalKey++
	cur := int(genHandTotalKey * 10000 / genHandTotal)
	if cur != genHandLastPrint {
		genHandLastPrint = cur

		now := time.Now().UnixMilli()
		per := float64(now-genHandBeginPrint) / float64(genHandTotalKey)
		fmt.Println("N" + strconv.Itoa(GenHandN) + " " + fmt.Sprint(cur) + "%% 需要" +
			fmt.Sprint(per*float64(genHandTotal-genHandTotalKey)/60/1000) + "分" +
			" 用时" + fmt.Sprint((now-genHandBeginPrint)/60/1000) + "分" + " 速度" +
			fmt.Sprint(float64(genHandTotalKey)/(float64(now-genHandBeginPrint)/1000)) + "条/秒")
	}
	genHandMu.Unlock()
}

// genHandCalc exhaustively enumerates every opponent hand and the remaining
// public cards, comparing each against the player's hand.
func genHandCalc(hand, pub []int) float64 {
	list := removeCounts(genAllCards(), hand)
	list = removeCounts(list, pub)
	sort.Ints(list)

	data := &genHandCalcData{}

	otherhand := make([]int, 2)
	Permutation(list, 0, 0, 2, otherhand, func(otherhand []int) {
		remaining := removeCounts(list, otherhand)

		leftpub := make([]int, 5-GenHandN)
		Permutation(remaining, 0, 0, 5-GenHandN, leftpub, func(leftpub []int) {
			genHandCalcCompare(data, hand, pub, leftpub, otherhand)
		})
	})

	return (float64(data.win) + float64(data.tie)*0.5) / float64(data.total)
}

func genHandCalcCompare(data *genHandCalcData, hand, pub, leftpub, otherhand []int) {
	var my, other []byte
	for _, i := range hand {
		my = append(my, byte(i))
	}
	for _, i := range pub {
		my = append(my, byte(i))
	}
	for _, i := range leftpub {
		my = append(my, byte(i))
	}

	for _, i := range otherhand {
		other = append(other, byte(i))
	}
	for _, i := range pub {
		other = append(other, byte(i))
	}
	for _, i := range leftpub {
		other = append(other, byte(i))
	}

	ret := CompareBytes(my, other)
	if ret == 0 {
		data.tie++
	} else if ret < 0 {
		data.lose++
	} else if ret > 0 {
		data.win++
	}
	data.total++
}

// removeCounts removes one occurrence of each value in remove from list,
// matching Java's repeated list.remove((Integer)p) semantics without mutating
// the input slice.
func removeCounts(list, remove []int) []int {
	cnt := map[int]int{}
	for _, p := range remove {
		cnt[p]++
	}
	var ret []int
	for _, x := range list {
		if cnt[x] > 0 {
			cnt[x]--
			continue
		}
		ret = append(ret, x)
	}
	return ret
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
