name: Go CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    strategy:
      matrix:
        go: [ '1.21', 'stable' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...
